# Generated by Django 4.1.7 on 2023-04-09 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('usageTime', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
