# Generated by Django 4.1.7 on 2023-03-14 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('usage_time', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('registration_date', models.DateTimeField(default=datetime.datetime(2023, 3, 13, 23, 54, 12, 27170))),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
