# Generated by Django 4.1.7 on 2023-03-14 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 0, 19, 7, 470334)),
        ),
    ]
