# Generated by Django 4.1.7 on 2023-04-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='usageTime',
        ),
    ]
