# Generated by Django 4.1.7 on 2023-04-02 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockAPI', '0002_alter_item_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 2, 17, 19, 53, 294651)),
        ),
    ]
