# Generated by Django 4.1.7 on 2023-04-09 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockAPI', '0003_alter_item_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='foto',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
