# Generated by Django 4.1.7 on 2023-03-23 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criador', models.CharField(max_length=100)),
                ('lance_inicial', models.DecimalField(decimal_places=2, max_digits=50)),
                ('lance_atual', models.DecimalField(decimal_places=2, max_digits=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_encerramento', models.DateTimeField()),
                ('arrematante', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=50)),
                ('horario_lance', models.DateTimeField(auto_now_add=True)),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.leilao')),
            ],
        ),
    ]
